name: Build QuteQoin

on: [push, pull_request]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Install tools
        run: apt install cppcheck

      - name: Run check
        run: cppcheck .


  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Install Qt (windows)
        uses: jurplel/install-qt-action@v2
        with:
          target: desktop
          host: windows
          arch: win64_mingw73
        if: startsWith(matrix.os, 'windows')

      - name: Install Qt (linux)
        run: sudo apt install qt-sdk
        if: startsWith(matrix.os, 'linux')

      - name: Prepare build
        run: qmake

      - name: Build
        run: make