name: Build QuteQoin

on: [push, pull_request]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Install tools
        run: sudo apt install cppcheck

      - name: Run check
        run: cppcheck .

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        qt: [default, "5.12.6"]
        exclude:
          - os: windows-latest
            qt: default
    steps:
      - name: Get sources
        uses: actions/checkout@v1

      - name: Install Qt (windows - ${{ matrix.qt }})
        if: startsWith(matrix.os, 'windows')
        uses: jurplel/install-qt-action@v2
        with:
          target: desktop
          host: windows
          arch: win64_mingw73
          version: ${{ matrix.qt }}

      - name: Install Qt (linux - ${{ matrix.qt }})
        if: startsWith(matrix.os, 'ubuntu') && ! startsWith(matrix.qt, 'default') 
        run: |
          sudo apt install python3-requests p7zip-full wget
          wget https://git.kaidan.im/lnj/qli-installer/raw/master/qli-installer.py
          chmod +x qli-installer.py
          ./qli-installer.py ${{ matrix.qt }} linux desktop

      - name: Install Qt (linux - default)
        if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.qt, 'default') 
        run: |
          sudo apt update
          sudo apt install qt5-default qt5-qmake qtbase5-dev qtmultimedia5-dev

      - name: Prepare build
        run: |
          export PATH=./${{ matrix.qt }}/gcc_64/:$PATH
          qmake

      - name: Build
        run: make